---
- name: Check httpd config
  ansible.builtin.command: apachectl configtest
  changed_when: false
  listen: Reload httpd

- name: Reload httpd service
  ansible.builtin.systemd_service:
    name: httpd
    state: reloaded
  listen: Reload httpd

- name: Restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted
